return {
	UnityEngine = {
		type = "lib",
		description="UnityEngine",
		childs = {
			Transform = {
				type = "lib",				
				description = "Transform",
				childs = {
					get_position = {
						type = "function",
						description = "Class:Transform.get_position",
						args = "()",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					set_position = {
						type = "function",
						description = "Class:Transform.set_position",
						args = "( Vector3 value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_localPosition = {
						type = "function",
						description = "Class:Transform.get_localPosition",
						args = "()",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					set_localPosition = {
						type = "function",
						description = "Class:Transform.set_localPosition",
						args = "( Vector3 value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_eulerAngles = {
						type = "function",
						description = "Class:Transform.get_eulerAngles",
						args = "()",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					set_eulerAngles = {
						type = "function",
						description = "Class:Transform.set_eulerAngles",
						args = "( Vector3 value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_localEulerAngles = {
						type = "function",
						description = "Class:Transform.get_localEulerAngles",
						args = "()",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					set_localEulerAngles = {
						type = "function",
						description = "Class:Transform.set_localEulerAngles",
						args = "( Vector3 value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_right = {
						type = "function",
						description = "Class:Transform.get_right",
						args = "()",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					set_right = {
						type = "function",
						description = "Class:Transform.set_right",
						args = "( Vector3 value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_up = {
						type = "function",
						description = "Class:Transform.get_up",
						args = "()",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					set_up = {
						type = "function",
						description = "Class:Transform.set_up",
						args = "( Vector3 value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_forward = {
						type = "function",
						description = "Class:Transform.get_forward",
						args = "()",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					set_forward = {
						type = "function",
						description = "Class:Transform.set_forward",
						args = "( Vector3 value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_rotation = {
						type = "function",
						description = "Class:Transform.get_rotation",
						args = "()",
						returns = "UnityEngine.Quaternion",
						valuetype = "UnityEngine.Quaternion",
					},
					set_rotation = {
						type = "function",
						description = "Class:Transform.set_rotation",
						args = "( Quaternion value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_localRotation = {
						type = "function",
						description = "Class:Transform.get_localRotation",
						args = "()",
						returns = "UnityEngine.Quaternion",
						valuetype = "UnityEngine.Quaternion",
					},
					set_localRotation = {
						type = "function",
						description = "Class:Transform.set_localRotation",
						args = "( Quaternion value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_localScale = {
						type = "function",
						description = "Class:Transform.get_localScale",
						args = "()",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					set_localScale = {
						type = "function",
						description = "Class:Transform.set_localScale",
						args = "( Vector3 value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_parent = {
						type = "function",
						description = "Class:Transform.get_parent",
						args = "()",
						returns = "UnityEngine.Transform",
						valuetype = "UnityEngine.Transform",
					},
					set_parent = {
						type = "function",
						description = "Class:Transform.set_parent",
						args = "( Transform value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SetParent = {
						type = "function",
						description = "Class:Transform.SetParent",
						args = "( Transform parent )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SetParent = {
						type = "function",
						description = "Class:Transform.SetParent",
						args = "( Transform parent, Boolean worldPositionStays )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_worldToLocalMatrix = {
						type = "function",
						description = "Class:Transform.get_worldToLocalMatrix",
						args = "()",
						returns = "UnityEngine.Matrix4x4",
						valuetype = "UnityEngine.Matrix4x4",
					},
					get_localToWorldMatrix = {
						type = "function",
						description = "Class:Transform.get_localToWorldMatrix",
						args = "()",
						returns = "UnityEngine.Matrix4x4",
						valuetype = "UnityEngine.Matrix4x4",
					},
					Translate = {
						type = "function",
						description = "Class:Transform.Translate",
						args = "( Vector3 translation )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Translate = {
						type = "function",
						description = "Class:Transform.Translate",
						args = "( Vector3 translation, Space relativeTo )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Translate = {
						type = "function",
						description = "Class:Transform.Translate",
						args = "( Single x, Single y, Single z )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Translate = {
						type = "function",
						description = "Class:Transform.Translate",
						args = "( Single x, Single y, Single z, Space relativeTo )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Translate = {
						type = "function",
						description = "Class:Transform.Translate",
						args = "( Vector3 translation, Transform relativeTo )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Translate = {
						type = "function",
						description = "Class:Transform.Translate",
						args = "( Single x, Single y, Single z, Transform relativeTo )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Rotate = {
						type = "function",
						description = "Class:Transform.Rotate",
						args = "( Vector3 eulerAngles )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Rotate = {
						type = "function",
						description = "Class:Transform.Rotate",
						args = "( Vector3 eulerAngles, Space relativeTo )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Rotate = {
						type = "function",
						description = "Class:Transform.Rotate",
						args = "( Single xAngle, Single yAngle, Single zAngle )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Rotate = {
						type = "function",
						description = "Class:Transform.Rotate",
						args = "( Single xAngle, Single yAngle, Single zAngle, Space relativeTo )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Rotate = {
						type = "function",
						description = "Class:Transform.Rotate",
						args = "( Vector3 axis, Single angle )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Rotate = {
						type = "function",
						description = "Class:Transform.Rotate",
						args = "( Vector3 axis, Single angle, Space relativeTo )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					RotateAround = {
						type = "function",
						description = "Class:Transform.RotateAround",
						args = "( Vector3 point, Vector3 axis, Single angle )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					LookAt = {
						type = "function",
						description = "Class:Transform.LookAt",
						args = "( Transform target )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					LookAt = {
						type = "function",
						description = "Class:Transform.LookAt",
						args = "( Transform target, Vector3 worldUp )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					LookAt = {
						type = "function",
						description = "Class:Transform.LookAt",
						args = "( Vector3 worldPosition, Vector3 worldUp )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					LookAt = {
						type = "function",
						description = "Class:Transform.LookAt",
						args = "( Vector3 worldPosition )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					TransformDirection = {
						type = "function",
						description = "Class:Transform.TransformDirection",
						args = "( Vector3 direction )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					TransformDirection = {
						type = "function",
						description = "Class:Transform.TransformDirection",
						args = "( Single x, Single y, Single z )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					InverseTransformDirection = {
						type = "function",
						description = "Class:Transform.InverseTransformDirection",
						args = "( Vector3 direction )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					InverseTransformDirection = {
						type = "function",
						description = "Class:Transform.InverseTransformDirection",
						args = "( Single x, Single y, Single z )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					TransformVector = {
						type = "function",
						description = "Class:Transform.TransformVector",
						args = "( Vector3 vector )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					TransformVector = {
						type = "function",
						description = "Class:Transform.TransformVector",
						args = "( Single x, Single y, Single z )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					InverseTransformVector = {
						type = "function",
						description = "Class:Transform.InverseTransformVector",
						args = "( Vector3 vector )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					InverseTransformVector = {
						type = "function",
						description = "Class:Transform.InverseTransformVector",
						args = "( Single x, Single y, Single z )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					TransformPoint = {
						type = "function",
						description = "Class:Transform.TransformPoint",
						args = "( Vector3 position )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					TransformPoint = {
						type = "function",
						description = "Class:Transform.TransformPoint",
						args = "( Single x, Single y, Single z )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					InverseTransformPoint = {
						type = "function",
						description = "Class:Transform.InverseTransformPoint",
						args = "( Vector3 position )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					InverseTransformPoint = {
						type = "function",
						description = "Class:Transform.InverseTransformPoint",
						args = "( Single x, Single y, Single z )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					get_root = {
						type = "function",
						description = "Class:Transform.get_root",
						args = "()",
						returns = "UnityEngine.Transform",
						valuetype = "UnityEngine.Transform",
					},
					get_childCount = {
						type = "function",
						description = "Class:Transform.get_childCount",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					DetachChildren = {
						type = "function",
						description = "Class:Transform.DetachChildren",
						args = "()",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SetAsFirstSibling = {
						type = "function",
						description = "Class:Transform.SetAsFirstSibling",
						args = "()",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SetAsLastSibling = {
						type = "function",
						description = "Class:Transform.SetAsLastSibling",
						args = "()",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SetSiblingIndex = {
						type = "function",
						description = "Class:Transform.SetSiblingIndex",
						args = "( Int32 index )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					GetSiblingIndex = {
						type = "function",
						description = "Class:Transform.GetSiblingIndex",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					Find = {
						type = "function",
						description = "Class:Transform.Find",
						args = "( System.String name )",
						returns = "UnityEngine.Transform",
						valuetype = "UnityEngine.Transform",
					},
					get_lossyScale = {
						type = "function",
						description = "Class:Transform.get_lossyScale",
						args = "()",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					IsChildOf = {
						type = "function",
						description = "Class:Transform.IsChildOf",
						args = "( Transform parent )",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					get_hasChanged = {
						type = "function",
						description = "Class:Transform.get_hasChanged",
						args = "()",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					set_hasChanged = {
						type = "function",
						description = "Class:Transform.set_hasChanged",
						args = "( Boolean value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					FindChild = {
						type = "function",
						description = "Class:Transform.FindChild",
						args = "( System.String name )",
						returns = "UnityEngine.Transform",
						valuetype = "UnityEngine.Transform",
					},
					GetEnumerator = {
						type = "function",
						description = "Class:Transform.GetEnumerator",
						args = "()",
						returns = "System.Collections.IEnumerator",
						valuetype = "System.Collections.IEnumerator",
					},
					RotateAround = {
						type = "function",
						description = "Class:Transform.RotateAround",
						args = "( Vector3 axis, Single angle )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					RotateAroundLocal = {
						type = "function",
						description = "Class:Transform.RotateAroundLocal",
						args = "( Vector3 axis, Single angle )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					GetChild = {
						type = "function",
						description = "Class:Transform.GetChild",
						args = "( Int32 index )",
						returns = "UnityEngine.Transform",
						valuetype = "UnityEngine.Transform",
					},
					GetChildCount = {
						type = "function",
						description = "Class:Transform.GetChildCount",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					get_hierarchyCapacity = {
						type = "function",
						description = "Class:Transform.get_hierarchyCapacity",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					set_hierarchyCapacity = {
						type = "function",
						description = "Class:Transform.set_hierarchyCapacity",
						args = "( Int32 value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_hierarchyCount = {
						type = "function",
						description = "Class:Transform.get_hierarchyCount",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					get_transform = {
						type = "function",
						description = "Class:Transform.get_transform",
						args = "()",
						returns = "UnityEngine.Transform",
						valuetype = "UnityEngine.Transform",
					},
					get_gameObject = {
						type = "function",
						description = "Class:Transform.get_gameObject",
						args = "()",
						returns = "UnityEngine.GameObject",
						valuetype = "UnityEngine.GameObject",
					},
					GetComponent = {
						type = "function",
						description = "Class:Transform.GetComponent",
						args = "( System.Type type )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					GetComponent = {
						type = "function",
						description = "Class:Transform.GetComponent",
						args = "( System.String type )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					GetComponentInChildren = {
						type = "function",
						description = "Class:Transform.GetComponentInChildren",
						args = "( System.Type t, Boolean includeInactive )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					GetComponentInChildren = {
						type = "function",
						description = "Class:Transform.GetComponentInChildren",
						args = "( System.Type t )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					GetComponentsInChildren = {
						type = "function",
						description = "Class:Transform.GetComponentsInChildren",
						args = "( System.Type t )",
						returns = "UnityEngine.Component[]",
						valuetype = "UnityEngine.Component[]",
					},
					GetComponentsInChildren = {
						type = "function",
						description = "Class:Transform.GetComponentsInChildren",
						args = "( System.Type t, Boolean includeInactive )",
						returns = "UnityEngine.Component[]",
						valuetype = "UnityEngine.Component[]",
					},
					GetComponentInParent = {
						type = "function",
						description = "Class:Transform.GetComponentInParent",
						args = "( System.Type t )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					GetComponentsInParent = {
						type = "function",
						description = "Class:Transform.GetComponentsInParent",
						args = "( System.Type t )",
						returns = "UnityEngine.Component[]",
						valuetype = "UnityEngine.Component[]",
					},
					GetComponentsInParent = {
						type = "function",
						description = "Class:Transform.GetComponentsInParent",
						args = "( System.Type t, Boolean includeInactive )",
						returns = "UnityEngine.Component[]",
						valuetype = "UnityEngine.Component[]",
					},
					GetComponents = {
						type = "function",
						description = "Class:Transform.GetComponents",
						args = "( System.Type type )",
						returns = "UnityEngine.Component[]",
						valuetype = "UnityEngine.Component[]",
					},
					GetComponents = {
						type = "function",
						description = "Class:Transform.GetComponents",
						args = "( System.Type type, System.Collections.Generic.List`1[[UnityEngine.Component, UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]] results )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_tag = {
						type = "function",
						description = "Class:Transform.get_tag",
						args = "()",
						returns = "System.String",
						valuetype = "System.String",
					},
					set_tag = {
						type = "function",
						description = "Class:Transform.set_tag",
						args = "( System.String value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					CompareTag = {
						type = "function",
						description = "Class:Transform.CompareTag",
						args = "( System.String tag )",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					SendMessageUpwards = {
						type = "function",
						description = "Class:Transform.SendMessageUpwards",
						args = "( System.String methodName, System.Object value, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessageUpwards = {
						type = "function",
						description = "Class:Transform.SendMessageUpwards",
						args = "( System.String methodName, System.Object value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessageUpwards = {
						type = "function",
						description = "Class:Transform.SendMessageUpwards",
						args = "( System.String methodName )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessageUpwards = {
						type = "function",
						description = "Class:Transform.SendMessageUpwards",
						args = "( System.String methodName, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessage = {
						type = "function",
						description = "Class:Transform.SendMessage",
						args = "( System.String methodName, System.Object value, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessage = {
						type = "function",
						description = "Class:Transform.SendMessage",
						args = "( System.String methodName, System.Object value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessage = {
						type = "function",
						description = "Class:Transform.SendMessage",
						args = "( System.String methodName )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessage = {
						type = "function",
						description = "Class:Transform.SendMessage",
						args = "( System.String methodName, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					BroadcastMessage = {
						type = "function",
						description = "Class:Transform.BroadcastMessage",
						args = "( System.String methodName, System.Object parameter, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					BroadcastMessage = {
						type = "function",
						description = "Class:Transform.BroadcastMessage",
						args = "( System.String methodName, System.Object parameter )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					BroadcastMessage = {
						type = "function",
						description = "Class:Transform.BroadcastMessage",
						args = "( System.String methodName )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					BroadcastMessage = {
						type = "function",
						description = "Class:Transform.BroadcastMessage",
						args = "( System.String methodName, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_rigidbody = {
						type = "function",
						description = "Class:Transform.get_rigidbody",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_rigidbody2D = {
						type = "function",
						description = "Class:Transform.get_rigidbody2D",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_camera = {
						type = "function",
						description = "Class:Transform.get_camera",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_light = {
						type = "function",
						description = "Class:Transform.get_light",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_animation = {
						type = "function",
						description = "Class:Transform.get_animation",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_constantForce = {
						type = "function",
						description = "Class:Transform.get_constantForce",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_renderer = {
						type = "function",
						description = "Class:Transform.get_renderer",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_audio = {
						type = "function",
						description = "Class:Transform.get_audio",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_guiText = {
						type = "function",
						description = "Class:Transform.get_guiText",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_networkView = {
						type = "function",
						description = "Class:Transform.get_networkView",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_guiElement = {
						type = "function",
						description = "Class:Transform.get_guiElement",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_guiTexture = {
						type = "function",
						description = "Class:Transform.get_guiTexture",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_collider = {
						type = "function",
						description = "Class:Transform.get_collider",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_collider2D = {
						type = "function",
						description = "Class:Transform.get_collider2D",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_hingeJoint = {
						type = "function",
						description = "Class:Transform.get_hingeJoint",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_particleEmitter = {
						type = "function",
						description = "Class:Transform.get_particleEmitter",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_particleSystem = {
						type = "function",
						description = "Class:Transform.get_particleSystem",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_name = {
						type = "function",
						description = "Class:Transform.get_name",
						args = "()",
						returns = "System.String",
						valuetype = "System.String",
					},
					set_name = {
						type = "function",
						description = "Class:Transform.set_name",
						args = "( System.String value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_hideFlags = {
						type = "function",
						description = "Class:Transform.get_hideFlags",
						args = "()",
						returns = "UnityEngine.HideFlags",
						valuetype = "UnityEngine.HideFlags",
					},
					set_hideFlags = {
						type = "function",
						description = "Class:Transform.set_hideFlags",
						args = "( HideFlags value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					ToString = {
						type = "function",
						description = "Class:Transform.ToString",
						args = "()",
						returns = "System.String",
						valuetype = "System.String",
					},
					GetInstanceID = {
						type = "function",
						description = "Class:Transform.GetInstanceID",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					GetHashCode = {
						type = "function",
						description = "Class:Transform.GetHashCode",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					Equals = {
						type = "function",
						description = "Class:Transform.Equals",
						args = "( System.Object other )",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					GetType = {
						type = "function",
						description = "Class:Transform.GetType",
						args = "()",
						returns = "System.Type",
						valuetype = "System.Type",
					},

				},
			},
			GameObject = {
				type = "lib",				
				description = "GameObject",
				childs = {
					CreatePrimitive = {
						type = "function",
						description = "Class:GameObject.CreatePrimitive",
						args = "( PrimitiveType type )",
						returns = "UnityEngine.GameObject",
						valuetype = "UnityEngine.GameObject",
					},
					GetComponent = {
						type = "function",
						description = "Class:GameObject.GetComponent",
						args = "( System.Type type )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					GetComponent = {
						type = "function",
						description = "Class:GameObject.GetComponent",
						args = "( System.String type )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					GetComponentInChildren = {
						type = "function",
						description = "Class:GameObject.GetComponentInChildren",
						args = "( System.Type type, Boolean includeInactive )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					GetComponentInChildren = {
						type = "function",
						description = "Class:GameObject.GetComponentInChildren",
						args = "( System.Type type )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					GetComponentInParent = {
						type = "function",
						description = "Class:GameObject.GetComponentInParent",
						args = "( System.Type type )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					GetComponents = {
						type = "function",
						description = "Class:GameObject.GetComponents",
						args = "( System.Type type )",
						returns = "UnityEngine.Component[]",
						valuetype = "UnityEngine.Component[]",
					},
					GetComponents = {
						type = "function",
						description = "Class:GameObject.GetComponents",
						args = "( System.Type type, System.Collections.Generic.List`1[[UnityEngine.Component, UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]] results )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					GetComponentsInChildren = {
						type = "function",
						description = "Class:GameObject.GetComponentsInChildren",
						args = "( System.Type type )",
						returns = "UnityEngine.Component[]",
						valuetype = "UnityEngine.Component[]",
					},
					GetComponentsInChildren = {
						type = "function",
						description = "Class:GameObject.GetComponentsInChildren",
						args = "( System.Type type, Boolean includeInactive )",
						returns = "UnityEngine.Component[]",
						valuetype = "UnityEngine.Component[]",
					},
					GetComponentsInParent = {
						type = "function",
						description = "Class:GameObject.GetComponentsInParent",
						args = "( System.Type type )",
						returns = "UnityEngine.Component[]",
						valuetype = "UnityEngine.Component[]",
					},
					GetComponentsInParent = {
						type = "function",
						description = "Class:GameObject.GetComponentsInParent",
						args = "( System.Type type, Boolean includeInactive )",
						returns = "UnityEngine.Component[]",
						valuetype = "UnityEngine.Component[]",
					},
					get_transform = {
						type = "function",
						description = "Class:GameObject.get_transform",
						args = "()",
						returns = "UnityEngine.Transform",
						valuetype = "UnityEngine.Transform",
					},
					get_layer = {
						type = "function",
						description = "Class:GameObject.get_layer",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					set_layer = {
						type = "function",
						description = "Class:GameObject.set_layer",
						args = "( Int32 value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_active = {
						type = "function",
						description = "Class:GameObject.get_active",
						args = "()",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					set_active = {
						type = "function",
						description = "Class:GameObject.set_active",
						args = "( Boolean value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SetActive = {
						type = "function",
						description = "Class:GameObject.SetActive",
						args = "( Boolean value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_activeSelf = {
						type = "function",
						description = "Class:GameObject.get_activeSelf",
						args = "()",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					get_activeInHierarchy = {
						type = "function",
						description = "Class:GameObject.get_activeInHierarchy",
						args = "()",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					SetActiveRecursively = {
						type = "function",
						description = "Class:GameObject.SetActiveRecursively",
						args = "( Boolean state )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_isStatic = {
						type = "function",
						description = "Class:GameObject.get_isStatic",
						args = "()",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					set_isStatic = {
						type = "function",
						description = "Class:GameObject.set_isStatic",
						args = "( Boolean value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_tag = {
						type = "function",
						description = "Class:GameObject.get_tag",
						args = "()",
						returns = "System.String",
						valuetype = "System.String",
					},
					set_tag = {
						type = "function",
						description = "Class:GameObject.set_tag",
						args = "( System.String value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					CompareTag = {
						type = "function",
						description = "Class:GameObject.CompareTag",
						args = "( System.String tag )",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					FindGameObjectWithTag = {
						type = "function",
						description = "Class:GameObject.FindGameObjectWithTag",
						args = "( System.String tag )",
						returns = "UnityEngine.GameObject",
						valuetype = "UnityEngine.GameObject",
					},
					FindWithTag = {
						type = "function",
						description = "Class:GameObject.FindWithTag",
						args = "( System.String tag )",
						returns = "UnityEngine.GameObject",
						valuetype = "UnityEngine.GameObject",
					},
					FindGameObjectsWithTag = {
						type = "function",
						description = "Class:GameObject.FindGameObjectsWithTag",
						args = "( System.String tag )",
						returns = "UnityEngine.GameObject[]",
						valuetype = "UnityEngine.GameObject[]",
					},
					SendMessageUpwards = {
						type = "function",
						description = "Class:GameObject.SendMessageUpwards",
						args = "( System.String methodName, System.Object value, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessageUpwards = {
						type = "function",
						description = "Class:GameObject.SendMessageUpwards",
						args = "( System.String methodName, System.Object value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessageUpwards = {
						type = "function",
						description = "Class:GameObject.SendMessageUpwards",
						args = "( System.String methodName )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessageUpwards = {
						type = "function",
						description = "Class:GameObject.SendMessageUpwards",
						args = "( System.String methodName, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessage = {
						type = "function",
						description = "Class:GameObject.SendMessage",
						args = "( System.String methodName, System.Object value, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessage = {
						type = "function",
						description = "Class:GameObject.SendMessage",
						args = "( System.String methodName, System.Object value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessage = {
						type = "function",
						description = "Class:GameObject.SendMessage",
						args = "( System.String methodName )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					SendMessage = {
						type = "function",
						description = "Class:GameObject.SendMessage",
						args = "( System.String methodName, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					BroadcastMessage = {
						type = "function",
						description = "Class:GameObject.BroadcastMessage",
						args = "( System.String methodName, System.Object parameter, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					BroadcastMessage = {
						type = "function",
						description = "Class:GameObject.BroadcastMessage",
						args = "( System.String methodName, System.Object parameter )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					BroadcastMessage = {
						type = "function",
						description = "Class:GameObject.BroadcastMessage",
						args = "( System.String methodName )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					BroadcastMessage = {
						type = "function",
						description = "Class:GameObject.BroadcastMessage",
						args = "( System.String methodName, SendMessageOptions options )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					AddComponent = {
						type = "function",
						description = "Class:GameObject.AddComponent",
						args = "( System.Type componentType )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					Find = {
						type = "function",
						description = "Class:GameObject.Find",
						args = "( System.String name )",
						returns = "UnityEngine.GameObject",
						valuetype = "UnityEngine.GameObject",
					},
					get_scene = {
						type = "function",
						description = "Class:GameObject.get_scene",
						args = "()",
						returns = "UnityEngine.SceneManagement.Scene",
						valuetype = "UnityEngine.SceneManagement.Scene",
					},
					get_gameObject = {
						type = "function",
						description = "Class:GameObject.get_gameObject",
						args = "()",
						returns = "UnityEngine.GameObject",
						valuetype = "UnityEngine.GameObject",
					},
					SampleAnimation = {
						type = "function",
						description = "Class:GameObject.SampleAnimation",
						args = "( Object clip, Single time )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					AddComponent = {
						type = "function",
						description = "Class:GameObject.AddComponent",
						args = "( System.String className )",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_rigidbody = {
						type = "function",
						description = "Class:GameObject.get_rigidbody",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_rigidbody2D = {
						type = "function",
						description = "Class:GameObject.get_rigidbody2D",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_camera = {
						type = "function",
						description = "Class:GameObject.get_camera",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_light = {
						type = "function",
						description = "Class:GameObject.get_light",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_animation = {
						type = "function",
						description = "Class:GameObject.get_animation",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_constantForce = {
						type = "function",
						description = "Class:GameObject.get_constantForce",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_renderer = {
						type = "function",
						description = "Class:GameObject.get_renderer",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_audio = {
						type = "function",
						description = "Class:GameObject.get_audio",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_guiText = {
						type = "function",
						description = "Class:GameObject.get_guiText",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_networkView = {
						type = "function",
						description = "Class:GameObject.get_networkView",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_guiElement = {
						type = "function",
						description = "Class:GameObject.get_guiElement",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_guiTexture = {
						type = "function",
						description = "Class:GameObject.get_guiTexture",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_collider = {
						type = "function",
						description = "Class:GameObject.get_collider",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_collider2D = {
						type = "function",
						description = "Class:GameObject.get_collider2D",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_hingeJoint = {
						type = "function",
						description = "Class:GameObject.get_hingeJoint",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_particleEmitter = {
						type = "function",
						description = "Class:GameObject.get_particleEmitter",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					get_particleSystem = {
						type = "function",
						description = "Class:GameObject.get_particleSystem",
						args = "()",
						returns = "UnityEngine.Component",
						valuetype = "UnityEngine.Component",
					},
					PlayAnimation = {
						type = "function",
						description = "Class:GameObject.PlayAnimation",
						args = "( Object animation )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					StopAnimation = {
						type = "function",
						description = "Class:GameObject.StopAnimation",
						args = "()",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_name = {
						type = "function",
						description = "Class:GameObject.get_name",
						args = "()",
						returns = "System.String",
						valuetype = "System.String",
					},
					set_name = {
						type = "function",
						description = "Class:GameObject.set_name",
						args = "( System.String value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_hideFlags = {
						type = "function",
						description = "Class:GameObject.get_hideFlags",
						args = "()",
						returns = "UnityEngine.HideFlags",
						valuetype = "UnityEngine.HideFlags",
					},
					set_hideFlags = {
						type = "function",
						description = "Class:GameObject.set_hideFlags",
						args = "( HideFlags value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					ToString = {
						type = "function",
						description = "Class:GameObject.ToString",
						args = "()",
						returns = "System.String",
						valuetype = "System.String",
					},
					GetInstanceID = {
						type = "function",
						description = "Class:GameObject.GetInstanceID",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					GetHashCode = {
						type = "function",
						description = "Class:GameObject.GetHashCode",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					Equals = {
						type = "function",
						description = "Class:GameObject.Equals",
						args = "( System.Object other )",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					GetType = {
						type = "function",
						description = "Class:GameObject.GetType",
						args = "()",
						returns = "System.Type",
						valuetype = "System.Type",
					},

				},
			},
			Vector2 = {
				type = "lib",				
				description = "Vector2",
				childs = {
					get_Item = {
						type = "function",
						description = "Class:Vector2.get_Item",
						args = "( Int32 index )",
						returns = "System.Single",
						valuetype = "System.Single",
					},
					set_Item = {
						type = "function",
						description = "Class:Vector2.set_Item",
						args = "( Int32 index, Single value )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Set = {
						type = "function",
						description = "Class:Vector2.Set",
						args = "( Single newX, Single newY )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Lerp = {
						type = "function",
						description = "Class:Vector2.Lerp",
						args = "( Vector2 a, Vector2 b, Single t )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					LerpUnclamped = {
						type = "function",
						description = "Class:Vector2.LerpUnclamped",
						args = "( Vector2 a, Vector2 b, Single t )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					MoveTowards = {
						type = "function",
						description = "Class:Vector2.MoveTowards",
						args = "( Vector2 current, Vector2 target, Single maxDistanceDelta )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					Scale = {
						type = "function",
						description = "Class:Vector2.Scale",
						args = "( Vector2 a, Vector2 b )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					Scale = {
						type = "function",
						description = "Class:Vector2.Scale",
						args = "( Vector2 scale )",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					Normalize = {
						type = "function",
						description = "Class:Vector2.Normalize",
						args = "()",
						returns = "System.Void",
						valuetype = "System.Void",
					},
					get_normalized = {
						type = "function",
						description = "Class:Vector2.get_normalized",
						args = "()",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					ToString = {
						type = "function",
						description = "Class:Vector2.ToString",
						args = "()",
						returns = "System.String",
						valuetype = "System.String",
					},
					ToString = {
						type = "function",
						description = "Class:Vector2.ToString",
						args = "( System.String format )",
						returns = "System.String",
						valuetype = "System.String",
					},
					GetHashCode = {
						type = "function",
						description = "Class:Vector2.GetHashCode",
						args = "()",
						returns = "System.Int32",
						valuetype = "System.Int32",
					},
					Equals = {
						type = "function",
						description = "Class:Vector2.Equals",
						args = "( System.Object other )",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					Reflect = {
						type = "function",
						description = "Class:Vector2.Reflect",
						args = "( Vector2 inDirection, Vector2 inNormal )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					Dot = {
						type = "function",
						description = "Class:Vector2.Dot",
						args = "( Vector2 lhs, Vector2 rhs )",
						returns = "System.Single",
						valuetype = "System.Single",
					},
					get_magnitude = {
						type = "function",
						description = "Class:Vector2.get_magnitude",
						args = "()",
						returns = "System.Single",
						valuetype = "System.Single",
					},
					get_sqrMagnitude = {
						type = "function",
						description = "Class:Vector2.get_sqrMagnitude",
						args = "()",
						returns = "System.Single",
						valuetype = "System.Single",
					},
					Angle = {
						type = "function",
						description = "Class:Vector2.Angle",
						args = "( Vector2 from, Vector2 to )",
						returns = "System.Single",
						valuetype = "System.Single",
					},
					Distance = {
						type = "function",
						description = "Class:Vector2.Distance",
						args = "( Vector2 a, Vector2 b )",
						returns = "System.Single",
						valuetype = "System.Single",
					},
					ClampMagnitude = {
						type = "function",
						description = "Class:Vector2.ClampMagnitude",
						args = "( Vector2 vector, Single maxLength )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					SqrMagnitude = {
						type = "function",
						description = "Class:Vector2.SqrMagnitude",
						args = "( Vector2 a )",
						returns = "System.Single",
						valuetype = "System.Single",
					},
					SqrMagnitude = {
						type = "function",
						description = "Class:Vector2.SqrMagnitude",
						args = "()",
						returns = "System.Single",
						valuetype = "System.Single",
					},
					Min = {
						type = "function",
						description = "Class:Vector2.Min",
						args = "( Vector2 lhs, Vector2 rhs )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					Max = {
						type = "function",
						description = "Class:Vector2.Max",
						args = "( Vector2 lhs, Vector2 rhs )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					SmoothDamp = {
						type = "function",
						description = "Class:Vector2.SmoothDamp",
						args = "( Vector2 current, Vector2 target, Vector2& currentVelocity, Single smoothTime, Single maxSpeed, Single deltaTime )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					op_Addition = {
						type = "function",
						description = "Class:Vector2.op_Addition",
						args = "( Vector2 a, Vector2 b )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					op_Subtraction = {
						type = "function",
						description = "Class:Vector2.op_Subtraction",
						args = "( Vector2 a, Vector2 b )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					op_UnaryNegation = {
						type = "function",
						description = "Class:Vector2.op_UnaryNegation",
						args = "( Vector2 a )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					op_Multiply = {
						type = "function",
						description = "Class:Vector2.op_Multiply",
						args = "( Vector2 a, Single d )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					op_Multiply = {
						type = "function",
						description = "Class:Vector2.op_Multiply",
						args = "( Single d, Vector2 a )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					op_Division = {
						type = "function",
						description = "Class:Vector2.op_Division",
						args = "( Vector2 a, Single d )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					op_Equality = {
						type = "function",
						description = "Class:Vector2.op_Equality",
						args = "( Vector2 lhs, Vector2 rhs )",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					op_Inequality = {
						type = "function",
						description = "Class:Vector2.op_Inequality",
						args = "( Vector2 lhs, Vector2 rhs )",
						returns = "System.Boolean",
						valuetype = "System.Boolean",
					},
					op_Implicit = {
						type = "function",
						description = "Class:Vector2.op_Implicit",
						args = "( Vector3 v )",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					op_Implicit = {
						type = "function",
						description = "Class:Vector2.op_Implicit",
						args = "( Vector2 v )",
						returns = "UnityEngine.Vector3",
						valuetype = "UnityEngine.Vector3",
					},
					get_zero = {
						type = "function",
						description = "Class:Vector2.get_zero",
						args = "()",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					get_one = {
						type = "function",
						description = "Class:Vector2.get_one",
						args = "()",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					get_up = {
						type = "function",
						description = "Class:Vector2.get_up",
						args = "()",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					get_down = {
						type = "function",
						description = "Class:Vector2.get_down",
						args = "()",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					get_left = {
						type = "function",
						description = "Class:Vector2.get_left",
						args = "()",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					get_right = {
						type = "function",
						description = "Class:Vector2.get_right",
						args = "()",
						returns = "UnityEngine.Vector2",
						valuetype = "UnityEngine.Vector2",
					},
					GetType = {
						type = "function",
						description = "Class:Vector2.GetType",
						args = "()",
						returns = "System.Type",
						valuetype = "System.Type",
					},

				},
			},

		},
	},
}